# Generated by Django 3.0.8 on 2020-07-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='books',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
